[package]
name = "worker"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
aws-sdk-s3.workspace = true
common = { path = "../common" }
futures-util.workspace = true
redis.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
